project_id = "kabnbvnephjifeazaiis"

[functions.validate-api-key]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false
