project_id = "kabnbvnephjifeazaiis"

[functions.validate-api-key]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.analyze-titles]
verify_jwt = false

[functions.generate-scenes]
verify_jwt = false

[functions.analyze-transcript]
verify_jwt = false

[functions.analyze-channel]
verify_jwt = false

[functions.generate-tts]
verify_jwt = false

[functions.generate-imagefx]
verify_jwt = false

[functions.fetch-channel-videos]
verify_jwt = false

[functions.check-new-videos]
verify_jwt = false

[functions.fetch-youtube-analytics]
verify_jwt = false
